In [1]:
import numpy as np

In [6]:
ar1=np.array([0,1,2,3,4])
ar1

array([0, 1, 2, 3, 4])

In [7]:
ar2=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(ar2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(ar1.shape)

(5,)


In [9]:
print(ar2.shape)

(3, 3)


In [10]:
ar1.ndim

1

In [11]:
ar2.ndim

2

In [12]:
ar1.dtype

dtype('int64')

In [14]:
ar3=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [15]:
print(ar3)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
ar3.dtype

dtype('float64')

In [17]:
ar4=np.array([1,2,3.0])

In [18]:
ar4.dtype

dtype('float64')

In [19]:
ar5=np.array([1.0,2,'afdf'])

In [20]:
ar5.dtype

dtype('<U32')

In [21]:
ar1

array([0, 1, 2, 3, 4])

In [24]:
ar1=ar1.astype('int8')

In [25]:
ar1.dtype

dtype('int8')

In [26]:
np.zeros(4,)

array([0., 0., 0., 0.])

In [29]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.zeros((3,5),'int64')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.ones(4,)

array([1., 1., 1., 1.])

In [35]:
np.ones(4)

array([1., 1., 1., 1.])

In [36]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
list1=[1,2,3,4,5]

for i in range(0,len(list1)):
    list1[i]=list1[i]+1

print(list1)

[2, 3, 4, 5, 6]


In [43]:
ar_test=np.array(list1)
print(ar_test)
print(list1)

[2 3 4 5 6]
[2, 3, 4, 5, 6]


In [45]:
print(ar_test+1)

[3 4 5 6 7]


In [47]:
for i in np.arange(0,1,0.1):
    print(i)

0.0
0.1
0.2
0.30000000000000004
0.4
0.5
0.6000000000000001
0.7000000000000001
0.8
0.9


In [48]:
ar1=np.arange(10)

In [49]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
ar1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
ar2=np.arange(12)

In [52]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
ar2.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
ar2.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [60]:
ar1=np.array([1,2,3,4])
ar2=np.array([9,10,11,12])
np.dot(ar1,ar2)

110